spring:
  datasource:
    url: jdbc:mysql://<PROD_DB_HOST>:3306/anyang?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # 운영에서는 가능하면 validate 권장
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.example.An_Yang: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

apis:
  kakao:
    restKey: ${KAKAO_REST_KEY}
  ftc:
    serviceKey: ${FTC_SERVICE_KEY}
  seoul:
    key: ${SEOUL_OPENAPI_KEY}
  sbiz:
    serviceKey: ${SBIZ_SERVICE_KEY}
  mois:
    serviceKey: ${MOIS_SERVICE_KEY}

gemini:
  api-key: ${GEMINI_API_KEY}

jwt:
  secret: ${JWT_SECRET}
